### ISSUE TITLE
Feature Request:  Live Stream Input Option

### ISSUE THREAD

**Issue by tvadi** [ffplayout/ffplayout_engine#110]
First of all, thank you so much for all your help and getting me all set up with FFplayout working out Decklink, very awesome!
Now comes the next challenge, feel free to shoot me an email if that is better too..  asperi (at) hotmail (dot) com  
 
What I need is an option to take a live feed from OBS, most likely an SRT stream.  FFplayout could be configured to default to this stream and just pass it to the outputs (Decklink and RTMP).  But if the stream fails, goes black too long or gets too much errors, it automatically switches to the playlist like normal.  

Please let me know what you think, thanks!

**Comment by jb-alvarado** [comment]
ffplayout by it self has no support for that and at the moment there is also no plan for realising this feature. It was a little discuss [here](https://github.com/ffplayout/ffplayout_engine/issues/96). 
I understand the need and we also needing this feature, but we do it on HLS server side. You need something for decklink, a mixer would be good for that. Like:
https://github.com/Xingtao/FFdynamic
Or:
https://github.com/voc/voctomix

But because you are using decklink, why not using an Atem?

**Comment by tvadi** [comment]
Well that's a super bummer, especially since it has been requested so much.  You would not think it would be too hard to implement since the output is already established, just need to be able to patch in an input and override the file feed..    

So for this project, it is for an unmanned "headless" playout server.  Would live at a TV station, they switch to it for overnights or whenever they need something to play, but they never touch the box, it is managed remotely and just acts as a video source for their switcher.   That is why Atem will not work.   

Voctomix looks like it would have the same problems CasparCG and Vmix has for broadcast, it has layers, demux, mux, mixer..  With all that stuff you loose closed captions as are required by law in the states so anything like that cannot be used for broadcast.  That is was I love about ffplayout, with the right ffmpeg build, it is passing the captions perfectly.  Looks like FFdynamic may have the same issues Voctomix but I will give them a try..

If you get more open to adding an input I can see if I can raise some funds for this development if that would help..   Thanks!

**Comment by tvadi** [comment]
So excited to see this pushed to a commit!  Thank you for having a look at it.  Not to get too far ahead of myself but just wanted to explain what I have working so far.  
So got FFplayout working good, playing out Decklink SDi and passing CEA-708 closed captions.  To do this FFmpeg needs to be compiled with the Blackmagic SDK, that guide can be found here: [https://gist.github.com/afriza/879fed4ede539a5a6501e0f046f71463](url) and to get captions you will need libklvanc [https://github.com/stoth68000/libklvanc](url)  Having captions is super important, without them we cannot be on air so it is a priority for them to work.  
So everything works great for a file based playout server but there is always a need for a live input.  This is where OBS comes in.  OBS has an amazing "cloud closed captions" plug-in [https://github.com/ratwithacompiler/OBS-captions-plugin](url)  it uses Google Cloud Speech Recognition to listen to the audio from the live video happening on OBS and adds captions automatically.  OBS can output via SRT and it will pass the captions as CEA-608 closed captions.  This is something that was impossible a couple years ago or cost $30kUSD in equipment so it really is remarkable.  Thing is, the only way to get the captioned video to play out OBS is with SRT stream.  This is where the hope is that with an SRT input, the FFplayout user could use OBS for the live feed or just do the playlist like normal when a live feed is not needed.  Ideally there could be an input error/ dropout detection service and FFplayout would then switch to the playlist if the SRT feed fails (for an unmanned set up).  Also in an ideal world, the SRT captions would pass out Decklink the same as they are from the file playback.  To view the OBS plug in at work, simply install it, set source to caption, activate and stream by setting the stream server to Custom and service to:
`srt://127.0.0.1:10000?mode=listener`
Then, just open in MPV player:
`mpv srt://127.0.0.1:10000`
So hoping there is a way for the FFplayout input, if developed, to basically act the same as MPV in a way.  If the input is rtmp, not sure all this would work, but maybe there is a way for rtmp to pass captions too.  In talking with the developer of the plug in (ratwithacompiler) he said it only works with SRT.  Please let me know your thoughts and if there is anything I can do to help.  As always, thank you!

**Comment by jb-alvarado** [comment]
I made the ingest more generic, so you can use any ffmpeg supported input.

My compiler script also support decklink, if you want you can create a pull request for the caption lib.

**Comment by tvadi** [comment]
Cool, that should work for input, please let me know when/ how I can try it out.  No worries on the compiler, I don't mind making FFmpeg.  

So on the topic, is there a proper way to stop/ start everything FFplayout is doing?  Currently, even if I stop playback in the UI, the computer is still running ffmpeg and nginx so you cannot load ffmpeg or anything that also uses it.  Seems that way even after reboot.  Would be nice if there was like a master "on/off" switch or maybe there is something I am missing?

**Comment by jb-alvarado** [comment]
When you click stop button in UI the playout will stop. But ffplayout is made for 24/7 after a restart it will run again. There is no plan for temporary running. If you don't need 24/7 disable the systemd service. I you like you can also run the engine from the console, so you have it in your hand when to start or to stop.

And of course nginx will also run always.

**Comment by rasoolkhalifa** [comment]
> I made the ingest more generic, so you can use any ffmpeg supported input.
> 
> My compiler script also support decklink, if you want you can create a pull request for the caption lib.

Just tried out ffplayout and it's awesome! all I need is the ability to use hls or rtmp inputs in the playlists! are you still working on it or its already done?!

**Comment by tvadi** [comment]
I replaced the engine with the master engine repo uploaded 8 hours ago.  Where/ how do I configure the input?  Thanks!

**Comment by jb-alvarado** [comment]
Oh, I think at the moment is not so a good idea. For testing yes, you can use the master, but not for production. I have change  things in the config, and this is not compatible with the older version, and also not with the UI.

Any way, the input you can configure under `ingest`. But have in mind that there is no authentication, ffmpeg only listen to the give port and takes everything what comes in.

**Comment by tvadi** [comment]
Configure with ingest_server.py correct?   I am working to learn just running the engine from command line now.

**Comment by jb-alvarado** [comment]
Yes.

**Comment by jb-alvarado** [comment]
Just as a note: It can be that I skip ingest stream in the final version 4. At the moment I'm working on a [replacement](https://github.com/ffplayout/ffplayout-rs) and there it works more stable.

**Comment by jb-alvarado** [comment]
v4 is released, with live ingest.

**Comment by tvadi** [comment]
Hi.  Can you please give me an example of the best way to test the input?  What source do you use and code line to get it to work?  I have been meaning to try this again but would like to test with something that for sure works.  Thanks!
