### ISSUE TITLE
Question: Is there a way to have a single playlist every day?

### ISSUE THREAD

**Issue by gabek** [ffplayout/ffplayout_engine#112]
I'm looking to have a specific order to a collection of videos playout, but I don't want to recreate it every day.

This might very well exist, and I just didn't catch how to do it, but is there a way to set a single playlist to repeat all day, every day?

Side note: I'm using the frontend with the engine.

Thanks!

**Comment by jb-alvarado** [comment]
Hi,\
for that is the [--loop](https://github.com/ffplayout/ffplayout_engine#start-with-arguments) argument. This is not implemented in the frontend, but on command line.

**Comment by gabek** [comment]
Got it, thanks for the clarification!
