### ISSUE TITLE
Showing error while starting the service from 'sudo systemctl start ffplayout_engine'

### ISSUE THREAD

**Issue by manassinghai** [ffplayout/ffplayout_engine#114]
Hi, First of all, Thanks for creating and sharing this playout package as open source. Now I am using it in my recent project.
I have followed all the steps and guidelines as suggested by you but I am getting error while starting the service from this command 'sudo systemctl start ffplayout_engine'. 

I am sharing the log below for better clarification:

Mar 07 05:20:02 ip-***.***.**.** systemd[1]: ffplayout_engine.service: Main process exited, code=exited, status=1/FAILURE
Mar 07 05:20:02 ip-***.***.**.** systemd[1]: ffplayout_engine.service: Failed with result 'exit-code'.
Mar 07 05:20:03 ip-***.***.**.** systemd[1]: ffplayout_engine.service: Service hold-off time over, scheduling restart.
Mar 07 05:20:03 ip-***.***.**.** systemd[1]: ffplayout_engine.service: Scheduled restart job, restart counter is at 5.
Mar 07 05:20:03 ip-***.***.**.** systemd[1]: Stopped python and ffmpeg based playout.
Mar 07 05:20:03 ip-***.***.**.** systemd[1]: ffplayout_engine.service: Start request repeated too quickly.
Mar 07 05:20:03 ip-***.***.**.** systemd[1]: ffplayout_engine.service: Failed with result 'exit-code'.
Mar 07 05:20:03 ip-***.***.**.** systemd[1]: Failed to start python and ffmpeg based playout.

Mar  7 04:59:48 ip-***.***.**.** systemd[1]: ffplayout_engine.service: Service hold-off time over, scheduling restart.
Mar  7 04:59:48 ip-***.***.**.** systemd[1]: ffplayout_engine.service: Scheduled restart job, restart counter is at 1.
Mar  7 04:59:48 ip-***.***.**.** systemd[1]: Stopped python and ffmpeg based playout.
Mar  7 04:59:48 ip-***.***.**.** systemd[1]: Started python and ffmpeg based playout.
Mar  7 04:59:48 ip-***.***.**.** python[22589]: Traceback (most recent call last):
Mar  7 04:59:48 ip-***.***.**.** python[22589]:   File "/opt/ffplayout_engine/ffplayout.py", line 28, in <module>
Mar  7 04:59:48 ip-***.***.**.** python[22589]:     from ffplayout.utils import messenger, playout, validate_ffmpeg_libs
Mar  7 04:59:48 ip-***.***.**.** python[22589]:   File "/opt/ffplayout_engine/ffplayout/utils.py", line 45, in <module>
Mar  7 04:59:48 ip-***.***.**.** python[22589]:     import yaml
Mar  7 04:59:48 ip-***.***.**.** python[22589]: ModuleNotFoundError: No module named 'yaml'
Mar  7 04:59:48 ip-***.***.**.** systemd[1]: ffplayout_engine.service: Main process exited, code=exited, status=1/FAILURE
Mar  7 04:59:48 ip-***.***.**.** systemd[1]: ffplayout_engine.service: Failed with result 'exit-code'.

As per the log, it says that 'yaml' module is not found but when I check it, then it shows it is already installed. I am sharing the screenshot for the same.
![screenshot](https://user-images.githubusercontent.com/67833355/156996305-c6947467-1772-4aa4-bfba-a5721665b5f6.png)

I am using Ubuntu 18.04 and Python 3.6.9.

Any help will be really appreciated.
Thanks @jb-alvarado

**Comment by jb-alvarado** [comment]
Hi,
the supported python version is 3.7+. And when you are in the virtual environment, you can not install a python package with sudo. You have do do this step without sudo, because you want to install the package in the virtual environment and not under **/user/local/**.
